"""Upgrade field id in table User

Revision ID: 41fd08e4dcae
Revises: 84f9486ed355
Create Date: 2024-11-04 15:32:39.317505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41fd08e4dcae'
down_revision: Union[str, None] = '84f9486ed355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
