"""Create database

Revision ID: d806e5a1def7
Revises: 
Create Date: 2024-11-04 12:39:17.291901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd806e5a1def7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), autoincrement=True, nullable=False),
    sa.Column('update_at', sa.TIMESTAMP(), autoincrement=True, nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_event'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), autoincrement=True, nullable=False),
    sa.Column('update_at', sa.TIMESTAMP(), autoincrement=True, nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('preferences', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), autoincrement=True, nullable=False),
    sa.Column('update_at', sa.TIMESTAMP(), autoincrement=True, nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('external_url', sa.VARCHAR(), nullable=False),
    sa.Column('date_start', sa.DATE(), nullable=False),
    sa.Column('date_end', sa.DATE(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('is_cyclically', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_event.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    op.create_table('user_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), autoincrement=True, nullable=False),
    sa.Column('update_at', sa.TIMESTAMP(), autoincrement=True, nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('main_user', sa.Integer(), nullable=False),
    sa.Column('group_members', sa.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['main_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_group'))
    )
    op.create_table('user_to_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), autoincrement=True, nullable=False),
    sa.Column('update_at', sa.TIMESTAMP(), autoincrement=True, nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_to_event'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_to_event')
    op.drop_table('user_group')
    op.drop_table('event')
    op.drop_table('user')
    op.drop_table('group_event')
    # ### end Alembic commands ###
